<?php

require "../vendor/autoload.php";
require "../config/db.php";

use Dompdf\Dompdf;
use Dompdf\Options;


$from = $_GET["from"] ?? date("Y-m-d");
$to = $_GET["to"] ?? date("Y-m-d");
$status = $_GET["status"] ?? "All";



/* ==========================
   FETCH REPORT
========================== */


$sql = "
SELECT

students.reg_number,

students.first_name,

students.last_name,

attendance.status,

attendance.attendance_date

FROM attendance

JOIN students

ON attendance.student_id = students.id

WHERE attendance.attendance_date BETWEEN ? AND ?

";


$params = [$from,$to];

$types = "ss";



if($status != "All"){

    $sql .= " AND attendance.status = ? ";

    $params[] = $status;

    $types .= "s";

}



$sql .= "

ORDER BY attendance.attendance_date DESC,

students.reg_number

";



$stmt = $conn->prepare($sql);

$stmt->bind_param($types,...$params);

$stmt->execute();


$result = $stmt->get_result();



/* ==========================
   BUILD HTML
========================== */


$html = '

<!DOCTYPE html>

<html>

<head>

<style>


body{

font-family: Arial, sans-serif;

font-size:12px;

color:#333;

}



.header{

text-align:center;

margin-bottom:20px;

}



.title{

font-size:22px;

font-weight:bold;

color:#1e40af;

}



.subtitle{

color:#555;

}



.info{

margin-top:20px;

margin-bottom:20px;

padding:10px;

background:#f3f4f6;

border-radius:5px;

}



table{

width:100%;

border-collapse:collapse;

margin-top:15px;

}



th{

background:#1e40af;

color:white;

padding:10px;

text-align:center;

}



td{

border:1px solid #ddd;

padding:8px;

}



tr:nth-child(even){

background:#f9fafb;

}



.status-present{

color:green;

font-weight:bold;

}



.status-absent{

color:red;

font-weight:bold;

}



.status-late{

color:#d97706;

font-weight:bold;

}



.footer{

position:fixed;

bottom:-20px;

left:0;

right:0;

text-align:center;

font-size:10px;

color:#777;

}



</style>


</head>


<body>


<div class="header">


<div class="title">

AttendPro

</div>


<div class="subtitle">

Student Attendance Management System

</div>


<h3>

Attendance Report

</h3>


</div>



<div class="info">


<strong>Report Period:</strong>

'.$from.'

&nbsp; to &nbsp;

'.$to.'


<br><br>


<strong>Status Filter:</strong>

'.$status.'


<br><br>


<strong>Generated:</strong>

'.date("Y-m-d H:i").'


</div>




<table>


<tr>

<th>#</th>

<th>Reg Number</th>

<th>Student Name</th>

<th>Date</th>

<th>Status</th>

</tr>

';



$count=1;



while($row=$result->fetch_assoc()){


$statusClass = strtolower($row["status"]);



$html .= '

<tr>


<td>'.$count++.'</td>


<td>'.$row["reg_number"].'</td>


<td>

'.$row["first_name"].'

'.$row["last_name"].'

</td>


<td>

'.$row["attendance_date"].'

</td>


<td class="status-'.$statusClass.'">

'.$row["status"].'

</td>


</tr>


';


}



$html .= '

</table>



<div class="footer">

Generated by AttendPro Attendance System

</div>



</body>

</html>

';





/* ==========================
   GENERATE PDF
========================== */


$options = new Options();


$options->set("isHtml5ParserEnabled",true);

$options->set("isRemoteEnabled",true);



$dompdf = new Dompdf($options);



$dompdf->loadHtml($html);



$dompdf->setPaper(
    "A4",
    "portrait"
);



$dompdf->render();



$dompdf->stream(

"AttendPro_Attendance_Report.pdf",

[
    "Attachment"=>true
]

);



exit();

?>